
/** Special attributes that map to DOM events. */
export const eventNames = {
	onabort: 'abort',
	onanimationstart: 'animationstart',
	onanimationiteration: 'animationiteration',
	onanimationend: 'animationend',
	onblur: 'blur',
	oncanplay: 'canplay',
	oncanplaythrough: 'canplaythrough',
	onchange: 'change',
	onclick: 'click',
	oncontextmenu: 'contextmenu',
	oncopy: 'copy',
	oncut: 'cut',
	ondoubleclick: 'dblclick',
	ondrag: 'drag',
	ondragend: 'dragend',
	ondragenter: 'dragenter',
	ondragexit: 'dragexit',
	ondragleave: 'dragleave',
	ondragover: 'dragover',
	ondragstart: 'dragstart',
	ondrop: 'drop',
	ondurationchange: 'durationchange',
	onemptied: 'emptied',
	onencrypted: 'encrypted',
	onended: 'ended',
	onerror: 'error',
	onfocus: 'focus',
	oninput: 'input',
	oninvalid: 'invalid',
	onkeydown: 'keydown',
	onkeypress: 'keypress',
	onkeyup: 'keyup',
	onload: 'load',
	onloadeddata: 'loadeddata',
	onloadedmetadata: 'loadedmetadata',
	onloadstart: 'loadstart',
	onpause: 'pause',
	onplay: 'play',
	onplaying: 'playing',
	onprogress: 'progress',
	onmousedown: 'mousedown',
	onmouseenter: 'mouseenter',
	onmouseleave: 'mouseleave',
	onmousemove: 'mousemove',
	onmouseout: 'mouseout',
	onmouseover: 'mouseover',
	onmouseup: 'mouseup',
	onpaste: 'paste',
	onratechange: 'ratechange',
	onreset: 'reset',
	onscroll: 'scroll',
	onseeked: 'seeked',
	onseeking: 'seeking',
	onsubmit: 'submit',
	onstalled: 'stalled',
	onsuspend: 'suspend',
	ontimeupdate: 'timeupdate',
	ontransitionend: 'transitionend',
	ontouchcancel: 'touchcancel',
	ontouchend: 'touchend',
	ontouchmove: 'touchmove',
	ontouchstart: 'touchstart',
	onvolumechange: 'volumechange',
	onwaiting: 'waiting',
	onwheel: 'wheel'
}

/** Mouse event names */
export const mouseMvmntEventNames = [
	"onmouseenter",
	"onmouseleave",
	"onmousemove",
	"onmouseout",
	"onmouseover",
	"onmouseup"
]

export const svgTags = [
	"animate",
	"animateMotion",
	"animateTransform",

	"circle",
	"clipPath",
	"color-profile",

	"defs",
	"desc",
	"discard",

	"ellipse",

	"feBlend",
	"feColorMatrix",
	"feComponentTransfer",
	"feComposite",
	"feConvolveMatrix",
	"feDiffuseLighting",
	"feDisplacementMap",
	"feDistantLight",
	"feDropShadow",
	"feFlood",
	"feFuncA",
	"feFuncB",
	"feFuncG",
	"feFuncR",
	"feGaussianBlur",
	"feImage",
	"feMerge",
	"feMergeNode",
	"feMorphology",
	"feOffset",
	"fePointLight",
	"feSpecularLighting",
	"feSpotLight",
	"feTile",
	"feTurbulence",
	"filter",
	"foreignObject",

	"g",

	"hatch",
	"hatchpath",

	"image",

	"line",
	"linearGradient",

	"marker",
	"mask",
	"mesh",
	"meshgradient",
	"meshpatch",
	"meshrow",
	"metadata",
	"mpath",

	"path",
	"pattern",
	"polygon",
	"polyline",

	"radialGradient",
	"rect",

	//"script",
	"set",
	"solidcolor",
	"stop",
	//"style",
	"svg",
	"switch",
	"symbol",

	"text",
	"textPath",
	//"title",
	"tspan",

	"unknown",
	"use",

	"view"
]

export const selfClosingTags = [
	"area",
	"base",
	"br",
	"col",
	"embed",
	"hr",
	"img",
	"input",
	"link",
	"meta",
	"param",
	"source",
	"track",
	"wbr"
]
